apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-h2fu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-h2fu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-h2fu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-h2fu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-h2fu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tcrm-tenant/rhtap-demo-app/hacbs-test-project-h2fu@sha256:02f95f9fdc0f5558a10281f24db316ee729e6a03e6f37bb687909ed35c54f10b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
